src/Agui/GestBundle/Form/Type/AttachmentimagesType.php
<?php
namespace Agui\GestBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AttachmentimagesType extends AbstractType
{

    public function getParent()
    {
        return 'form';
    }

    public function getName()
    {
        return 'attachmentimages';
    }
}

src/Agui/GestBundle/Form/Type/DownloadattachmentType.php
<?php
namespace Agui\GestBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DownloadattachmentType extends AbstractType
{

    public function getParent()
    {
        return 'form';
    }

    public function getName()
    {
        return 'downloadattachment';
    }
}

src/Agui/GestBundle/Form/Type/IconType.php
<?php
namespace Agui\GestBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class IconType extends AbstractType
{
    
    public function getParent()
    {
        return 'form';
        
    }
    
    public function getName()
    {
        return 'icon';
    }
}

src/Agui/GestBundle/Form/Type/ImageType.php
<?php

namespace Agui\GestBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ImageType extends AbstractType
{
    
    public function getParent()
    {
        return 'form';
        
    }
    
    public function getName()
    {
        return 'image';
    }
}

src/Agui/GestBundle/Resources/views/Form/attachmentimages.html.twig
{% block attachmentimages_widget %}
	{% spaceless %}
		{% if value is not empty %}
			{% for attachmentimages in value %}
					{% set foo = 'productes/' ~ value %}
					<a class="fancybox" rel="attachmentimages" href="{{ foo | imagine_filter('mid_thumb') }}">
						<img src="{{ foo | imagine_filter('low_thumb') }}" alt="" />
					</a>
			{% endfor %}
		{% endif %}
	{% endspaceless %}
{% endblock %}

src/Agui/GestBundle/Resources/views/Form/downloadattachment.html.twig
{% block downloadattachment_widget %}
 {% spaceless %}
	 {% if value is not empty %}
			{# ruta: default_getattachment #}
			<a class="btn sonata-action-element" href="{{ path('default_getattachment', {'id': value}) }}">
				<i class="icon-download"></i>
				{{ 'Download file'|trans({}, 'SonataAdminBundle') }}
			</a>
	 {% endif %}
	 {% endspaceless %}
{% endblock %}

src/Agui/GestBundle/Resources/views/Form/form_admin_fields.html.twig
{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}

{% extends 'SonataAdminBundle:Form:form_admin_fields.html.twig' %}


{# Custom Sonata Admin Extension #}
{% block sonata_admin_orm_one_to_one_widget %}
    {% include 'SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_one.html.twig' %}
{% endblock %}

{% block sonata_admin_orm_many_to_many_widget %}
    {% include 'SonataDoctrineORMAdminBundle:CRUD:edit_orm_many_to_many.html.twig' %}
{% endblock %}

{% block sonata_admin_orm_many_to_one_widget %}
    {% include 'SonataDoctrineORMAdminBundle:CRUD:edit_orm_many_to_one.html.twig' %}
{% endblock %}

{% block sonata_admin_orm_one_to_many_widget %}
    {% include 'SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_many.html.twig' %}
{% endblock %}

{% block sonata_type_model_widget %}
    {#
        This is not the best way to do if
        TODO : improve this part
    #}

    {#model {{ sonata_admin.field_description.mappingtype }}#}

    {% if sonata_admin.field_description is empty %}
        {{ block('choice_widget') }}
    {% elseif sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::ONE_TO_ONE') %}
        {{ block('sonata_admin_orm_one_to_one_widget') }}
    {% elseif sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::MANY_TO_ONE') %}
        {{ block('sonata_admin_orm_many_to_one_widget') }}
    {% elseif sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::MANY_TO_MANY') %}
        {{ block('sonata_admin_orm_many_to_many_widget') }}
    {% elseif sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::ONE_TO_MANY') %}
        {{ block('sonata_admin_orm_one_to_many_widget') }}
    {% else %}
        {#INVALID MODE : {{ id }}#}
        {{ block('choice_widget') }}
    {% endif %}
{% endblock %}

{% block sonata_type_model_list_widget %}
    <div id="field_container_{{ id }}" class="field-container">
        <span id="field_actions_{{ id }}" class="field-actions">
            <span id="field_widget_{{ id }}" class="field-short-description">
                {% if sonata_admin.field_description.associationadmin.id(sonata_admin.value) %}
                    {% render url('sonata_admin_short_object_information', {
                        'code':     sonata_admin.field_description.associationadmin.code,
                        'objectId': sonata_admin.field_description.associationadmin.id(sonata_admin.value),
                        'uniqid':   sonata_admin.field_description.associationadmin.uniqid
                    }) %}
                {% elseif sonata_admin.field_description.options.placeholder is defined and sonata_admin.field_description.options.placeholder %}
                    <span class="inner-field-short-description">
                        {{ sonata_admin.field_description.options.placeholder|trans({}, 'SonataAdminBundle') }}
                    </span>
                {% endif %}
            </span>

            <span class="btn-group">
                {% if sonata_admin.field_description.associationadmin.hasroute('list') and sonata_admin.field_description.associationadmin.isGranted('LIST') and btn_list %}
                    <a  href="{{ sonata_admin.field_description.associationadmin.generateUrl('list') }}"
                        onclick="return start_field_dialog_form_list_{{ id }}(this);"
                        class="btn btn-small sonata-ba-action"
                        title="{{ btn_list|trans({}, btn_catalogue) }}"
                            >
                        <i class="icon-list"></i>
                        {{ btn_list|trans({}, btn_catalogue) }}
                    </a>
                {% endif %}

                {% if sonata_admin.field_description.associationadmin.hasroute('create') and sonata_admin.field_description.associationadmin.isGranted('CREATE') and btn_add %}
                    <a  href="{{ sonata_admin.field_description.associationadmin.generateUrl('create') }}"
                        onclick="return start_field_dialog_form_add_{{ id }}(this);"
                        class="btn btn-small sonata-ba-action"
                        title="{{ btn_add|trans({}, btn_catalogue) }}"
                            >
                        <i class="icon-plus"></i>
                        {{ btn_add|trans({}, btn_catalogue) }}
                    </a>
                {% endif %}
            </span>

            <span class="btn-group">
                {% if sonata_admin.field_description.associationadmin.hasRoute('delete') and sonata_admin.field_description.associationadmin.isGranted('DELETE') and btn_delete %}
                    <a  href=""
                        onclick="return remove_selected_element_{{ id }}(this);"
                        class="btn btn-small sonata-ba-action"
                        title="{{ btn_delete|trans({}, btn_catalogue) }}"
                            >
                        <i class="icon-off"></i>
                        {{ btn_delete|trans({}, btn_catalogue) }}
                    </a>
                {% endif %}
            </span>
        </span>

        <span style="display: none" >
            {{ form_widget(form) }}
        </span>

        <div class="container sonata-ba-modal sonata-ba-modal-edit-one-to-one" style="display: none" id="field_dialog_{{ id }}">

        </div>
    </div>

    {% include 'SonataDoctrineORMAdminBundle:CRUD:edit_orm_many_association_script.html.twig' %}
{% endblock %}

{% block sonata_type_admin_widget %}
    {#admin {{ sonata_admin.field_description.mappingtype }}#}
    {% if sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::ONE_TO_ONE') %}
        {{ block('sonata_admin_orm_one_to_one_widget') }}
    {% elseif sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::MANY_TO_ONE') %}
        {{ block('sonata_admin_orm_many_to_one_widget') }}
    {% elseif sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::MANY_TO_MANY') %}
        {{ block('sonata_admin_orm_many_to_many_widget') }}
    {% elseif sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::ONE_TO_MANY') %}
        {{ block('sonata_admin_orm_one_to_many_widget') }}
    {% else %}
        INVALID MODE : {{ id }}
    {% endif %}
{% endblock %}

{% block sonata_type_collection_widget %}
    {% if sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::ONE_TO_MANY') %}
        {{ block('sonata_admin_orm_one_to_many_widget') }}
    {% elseif sonata_admin.field_description.mappingtype == constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::MANY_TO_MANY') %}
        {{ block('sonata_admin_orm_many_to_many_widget') }}
    {% else %}
        INVALID MODE : {{ id }} - type : sonata_type_collection - mapping : {{ sonata_admin.field_description.mappingtype }}
    {% endif %}
{% endblock %}

src/Agui/GestBundle/Resources/views/Form/form_productsinfo_dashfilter.html.twig
{% block form_row %}
	{% if (form.vars.id != "form_priceto") %}
		<li class="control-group">
			<i class="icon-chevron-right"></i> {{ form.vars.label }}
			{% if (form.vars.id != "form_buscar") and (form.vars.id != "form_color")  %}
				<a href="{{ path('productsinfo_list') }}/action/hidefilter/{{ form.vars.id }}"><i class="icon-remove"></i></a><br />
			
			{% endif %}

			{{ form_errors(form) }}
			{{ form_widget(form) }}		
		</li>
	{% endif %}
{% endblock form_row %}

{% block _form_color_widget %}

	{% set options = choices %}
		
	<ul id="filter_colour" style=" margin: 2px; background-image:none; list-style: none;  ">
	{% for group_label, choice in options %}
		
		
		{% if choice.data.id == choice.data.parent.id %}
			{% if choice.label != '' %}

				<li id="{{ choice.value }}" style="{% if choice is selectedchoice(value) %}border:#888 2px solid;{% else %}border:#ddd 1px solid;{% endif %} display: list-item; float: left; margin: 3px;">
				<a href="#" data-trigger="hover" class="colorname" data-original-title="Grouped color" data-content="{{ choice.data.name|slice(4,20) }}" style="margin: 1px; float: left;{% if choice is selectedchoice(value) %}height:15px; width:15px; background-color: #{{ choice.label|trans({}, translation_domain) }};{% else %}height:17px; width:17px; background-color: #{{ choice.label|trans({}, translation_domain) }}; opacity: 0.6;{% endif %}"></a>
				{% if choice is selectedchoice(value) %}
					<input type="hidden" id="form_color" name="form[color][]" value="{{ choice.value }}" >
				{% endif %}
				</li>

			{% endif %}
		{% endif %}

	{% endfor %}
	</ul>

	</br></br></br>
	
{% endblock %}
		
{% block _form_pricefrom_widget %}
	
	<input type="text" id="form_pricefrom" name="form[pricefrom]" style="width: 50px" {% if value is not empty %}value="{{ value }}" {% endif %}> to
	<input type="text" id="form_priceto" name="form[priceto]" style="width: 50px" {% if value is not empty %}value="{{ value }}" {% endif %}>
		
{% endblock %}

src/Agui/GestBundle/Resources/views/Form/icon.html.twig
{% block icon_widget %}
	{% spaceless %}
		{% if value is not empty %}
			{% set foo = 'treeimages/' ~ value %}
			<a class="fancybox" href="{{ foo | imagine_filter('medium_thumb') }}"><img src="{{ foo | imagine_filter('my_thumb') }}" alt=""></a>
		{% endif%}
	{% endspaceless %}
{% endblock %}

src/Agui/GestBundle/Resources/views/Form/image.html.twig
{% block image_widget %}
	{% spaceless %}
		{% if value is not empty %}
			{% set foo = value %}
			<a class="fancybox" rel="fotos" href="{{ foo | imagine_filter('mid_thumb') }}"><img src="{{ foo | imagine_filter('low_thumb') }}" alt="" /></a>
		{% endif%}
	{% endspaceless %}
{% endblock %}

src/Agui/GestBundle/Resources/views/Form/incidences.html.twig
<div class="container-fluid">
	<h3 class="modal-title"></h3>
	{{ form_start(form, {'action': app.request.schemeAndHttpHost ~ app.request.getBaseURL() ~'/productsinfo/' ~ productid ~ '/postincidence/' ~ tipoincidencia,'attr': {'id':'formincidence', 'class':'form-horizontal'}} ) }}
		{{ form_errors(form) }}

		{% if tipoincidencia == 'pdf' %}
			<div class="control-group">
				<label class="control-label" for="form_to">To*:</label>
				<div class="controls">
					{{ form_errors(form.to) }}
					{{ form_widget(form.to) }}
				</div>
			</div>
		{% endif %}

		<div class="control-group">
			<label class="control-label" for="form_from">From*:</label>
			<div class="controls">
				{{ form_errors(form.from) }}
				{{ form_widget(form.from) }}
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="form_subject">Subject*:</label>
			<div class="controls">
				{{ form_errors(form.subject) }}
				{{ form_widget(form.subject) }}
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="form_message">Message*:</label>
			<div class="controls">
				{{ form_errors(form.message) }}
				{{ form_widget(form.message) }}
			</div>
		</div>

		{#<div class="clearfix" style="margin:10px 0">
			<button type="submit" id="form_save" name="form[save]" class="btn btn-primary pull-left">Send</button>
			<button type="button" id="form_cancel" name="form[cancel]" class="btn pull-left" data-dismiss="modal" style=>Cancel</button>
		</div>#}

		<div class="clearfix pull-right" style="margin:10px 0">
			{{ form_widget(form.save) }}
			{{ form_widget(form.cancel, {'style':'margin-left: 10px'})}}
		</div>

		{{ form_rest(form) }}

	{{ form_end(form) }}


</div>


{#% block button_row %}
	{% spaceless %}
	{% endspaceless %}
{% endblock button_row %#}

src/Agui/GestBundle/Resources/views/Form/registry.html.twig
{% block registry_widget %}
	{% spaceless %}
		{% if value is not empty %}
			<a href="{{ app.request.schemeAndHttpHost }}{{ app.request.getBaseURL() }}/graphics/registry/{{ value }}?_sonata_admin=sonata.admin.Graphics{#{ admin.graphics.generateUrl('graphics_download', '1') }#}" class="btn"> <i class="icon-download"></i> Download registry</a>
		{% endif %}
	{% endspaceless %}
{% endblock %}